// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using haircare.Models;

#nullable disable

namespace haircare.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241222132606_FixIslemPrimaryKey")]
    partial class FixIslemPrimaryKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("haircare.Models.Calisan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CalısanAd")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CalısanSoyad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UygunlukSaati")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UzmanlikAlani")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Calisanlar");
                });

            modelBuilder.Entity("haircare.Models.Islem", b =>
                {
                    b.Property<int>("IslemsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IslemsId"));

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("numeric");

                    b.Property<string>("IslemAd")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IslemSuresi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IslemTur")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IslemsId");

                    b.ToTable("Islemler");
                });

            modelBuilder.Entity("haircare.Models.Randevu", b =>
                {
                    b.Property<int>("randevuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("randevuId"));

                    b.Property<int>("CalisanId")
                        .HasColumnType("integer");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("islemId")
                        .HasColumnType("integer");

                    b.Property<int>("musteriId")
                        .HasColumnType("integer");

                    b.HasKey("randevuId");

                    b.HasIndex("CalisanId");

                    b.HasIndex("islemId");

                    b.HasIndex("musteriId");

                    b.ToTable("Randevular");
                });

            modelBuilder.Entity("haircare.Models.musteri", b =>
                {
                    b.Property<int>("musteriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("musteriId"));

                    b.Property<string>("kullanıcıAd")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("mail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("sifre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("telefonNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("musteriId");

                    b.ToTable("Musteriler");
                });

            modelBuilder.Entity("haircare.Models.Randevu", b =>
                {
                    b.HasOne("haircare.Models.Calisan", "Calisan")
                        .WithMany("Randevular")
                        .HasForeignKey("CalisanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("haircare.Models.Islem", "Islem")
                        .WithMany("Randevular")
                        .HasForeignKey("islemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("haircare.Models.musteri", "musteri")
                        .WithMany("Randevular")
                        .HasForeignKey("musteriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Calisan");

                    b.Navigation("Islem");

                    b.Navigation("musteri");
                });

            modelBuilder.Entity("haircare.Models.Calisan", b =>
                {
                    b.Navigation("Randevular");
                });

            modelBuilder.Entity("haircare.Models.Islem", b =>
                {
                    b.Navigation("Randevular");
                });

            modelBuilder.Entity("haircare.Models.musteri", b =>
                {
                    b.Navigation("Randevular");
                });
#pragma warning restore 612, 618
        }
    }
}
